# ~/.tmuxinator/inspire.yml
# you can make as many tabs as you wish...

project_name: dev
project_root: ~/Sites/inspire
# socket_name: foo # Not needed.  Remove to use default socket
# rvm: 1.9.2@rails_project
# pre: sudo /etc/rc.d/mysqld start
tabs:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - #empty, will just run plain bash
        - top
  - shell: git pull
  - database: be rails db
  - server: be rails s
  - logs: tail -f logs/development.log
  - console: be rails c
  - capistrano:
  - server: ssh inspire@inspirehq.com