# If not running interactively, don't do anything
if [[ ! -z "$PS1" ]]; then

for file in $HOME/$CONFIGS_PATH/bash/.{exports,awk,ssh,history,completion,alias,colors,completion,functions,bash_prompt}; do
  [ -r "$file" ] && source "$file"
done
unset file

# source $HOME/$CONFIGS_PATH/bash/ad
source $HOME/$CONFIGS_PATH/bash/ruby
source $HOME/$CONFIGS_PATH/bash/python

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

##
## better `cd`'ing
##

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

fi