# Flush DNS Cache
alias fcache='dscacheutil -flushcache'

# TextMate
alias m='mate'

# source $HOME/$CONFIGS_PATH/bash/ad
source $HOME/$CONFIGS_PATH/bash/awk
source $HOME/$CONFIGS_PATH/bash/colors
source $HOME/$CONFIGS_PATH/bash/git
source $HOME/$CONFIGS_PATH/bash/ruby
source $HOME/$CONFIGS_PATH/bash/ssh